module.exports = [
    ["Citizen Science","DIY culture","makerspaces","hackerspaces"],
    ["IoTs","Additive manufacturing","Digital fabrication","PC","mobile phones"],
    ["Bioprinting","Tissue Engineering","Artificial meat","Regenerative medicine","cloning"],
    ["Genetic engineering and gene editing"],
    ["Nanotechnology","Biomicrorobotics","Biobanking"],
    ["Synthetic Biology","Personalized Medicine"],
    ["Personalized medicine","proteomics","microbiome research"],
    ["Autonomous Vehicles","Drones"],
    ["Big data","open data","open gov"],
    ["Prosthesis","SENS rejuvenation"],
    ["Cryptocurrency and blockchain"],
    ["Wearable electronics","activity monitors","immune engineering"],
    ["Neurotechnology (TDCs","TMS","implants)","Brain computer interfaces"],
    ["Nanotechnologies"],
    ["Microfluidics","Lab on a chip technologies","Organs on a Chip"],
    ["Designer drugs","synthetic substances"],
    ["Nuclear energy"],
    ["Space travel","space exploration","Mission to Mars","search for habitable planets","reusable rockets"],
    ["VR technology","Laser","LEDs","new Military technology (directed energy weapons)"],
    ["Clean energy research","sustainable energy","Hydroelectric energy","solar energy","wind","geothermal","biomass"],
    ["Large Hadron Collider","quantum computing","swarm robotics"],
    ["World Wide Web","underwater cities","future cities"]
]