module.exports = [
    ["wastes","squanders","desacrates "],
    ["creates","inititates","develops"],
    ["supports","stabilizes","aids","maintains","assists"],
    ["challenges","changes"],
    ["consolidates","enforces"],
    ["restores","regulates"],
    ["prioritizes","streamlines","oversees"],
    ["envisions","encourages"],
    ["reviews","weights","inspects"],
    ["resonates on","isolates","stops"],
    ["reorganizes","transforms"],
    ["strengthens","selects","intervenes"],
    ["delegates","weakens"],
    ["terminates","destroys,annihilates"],
    ["negotiates","balances"],
    ["inflates","manipulates","escalates "],
    ["questions","makes unclear","ruins"],
    ["inspires","envisions","enlarges"],
    ["controls","destroys","transforms"],
    ["standardized","validates","supports"],
    ["reveals","opens"],
    ["improves","restores"]
]